# Generated by Django 4.1 on 2023-04-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_manufacturer_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='city',
        ),
    ]
