# Generated by Django 4.1 on 2023-09-23 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_driver_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('\\A[A-Z]{3}[0-9]{5}\\Z', message='Must Consist only of 8 characters First 3 characters are uppercase letters Last 5 characters are digits')]),
        ),
    ]
